### ISSUE TITLE
Add Run 2.2i DR6 repo

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/desc-dc2-dm-data#15]
I think it is available on NERSC scratch? @heather999 

(cc @fjaviersanchez)

**Comment by heather999** [comment]
The Run2.2i DR6 calibrated exposures are at NERSC as well as the subset of object catalogs that were previously transferred.  I will contact CC about potentially copying over any completed coadd/multiband data.

**Comment by yymao** [comment]
Added by #16
